### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity on Xperia Phones

### ISSUE THREAD

**Issue by MarcProe** [MarcProe/lp2go#33]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.librepilot.lp2go.beta/org.librepilot.lp2go.MainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.speech.tts.engine.CHECK_TTS_DATA }
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
    at android.app.ActivityThread.access$900(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:5526)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.speech.tts.engine.CHECK_TTS_DATA }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
    at android.app.Activity.startActivityForResult(Activity.java:3963)
    at android.app.Activity.startActivityForResult(Activity.java:3924)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
    at org.librepilot.lp2go.helper.TextToSpeechHelper.checkForTTS(TextToSpeechHelper.java:47)
    at org.librepilot.lp2go.helper.TextToSpeechHelper.<init>(TextToSpeechHelper.java:36)
    at org.librepilot.lp2go.MainActivity.onCreate(MainActivity.java:452)
    at android.app.Activity.performCreate(Activity.java:6285)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
    ... 9 more
```

**Comment by MarcProe** [comment]
![image](https://cloud.githubusercontent.com/assets/11455452/16463799/a7d35d7e-3e37-11e6-9673-3bcc2357da5a.png)
