### ISSUE TITLE
java.lang.NoClassDefFoundError on "wiko" phones

### ISSUE THREAD

**Issue by MarcProe** [MarcProe/lp2go#35]
```
java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
    at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:642)
    at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:864)
    at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:835)
    at android.support.v7.widget.ToolbarWidgetWrapper.getMenu(ToolbarWidgetWrapper.java:691)
    at android.support.v7.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:595)
    at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:447)
    at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
    at android.os.Handler.handleCallback(Handler.java:800)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5391)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by MarcProe** [comment]
looks like an old library in the android image on that phone.
